server:
  port: 3000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/bookparser
    username: postgres
    password: 123456

parsers:
  thread-pools: 8
